<a href="https://colab.research.google.com/github/MominulJM/Machine-Learning/blob/main/card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np
import pandas as pd 


In [94]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [95]:
df=pd.read_csv('/content/drive/MyDrive/Dataset/DATA/creditcard_FraudDetection_Dataset.csv')
df

Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

In [96]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [97]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [98]:
not_fraud=df[df.Class==0]
fraud=df[df.Class==1]
print(not_fraud.shape)
print(fraud.shape)

(284315, 31)
(492, 31)


In [99]:
not_fraud_sample=not_fraud.sample(n=600)
not_fraud_sample

Time        V1        V2  ...       V28  Amount  Class
37906    39163.0 -0.363913  0.853399  ... -0.257103   18.49      0
65786    51746.0 -3.519614  2.536332  ... -0.069912    3.84      0
160537  113441.0  2.049175 -0.073552  ... -0.060345    3.96      0
78817    57720.0  1.156016 -0.194637  ...  0.015398   12.04      0
265574  161946.0 -0.483227  1.349745  ...  0.079387    7.00      0
...          ...       ...       ...  ...       ...     ...    ...
180377  124514.0  1.742922 -0.647790  ... -0.017743   76.99      0
216570  140534.0  1.889312 -0.509207  ... -0.033884   15.74      0
36232    38446.0  1.073804 -0.186612  ...  0.019687    1.00      0
24640    33311.0 -0.462231  1.030745  ...  0.113105    0.89      0
167254  118574.0 -1.256499 -0.408368  ...  0.275238    1.00      0

[600 rows x 31 columns]

In [100]:
new_df=pd.concat([not_fraud_sample,fraud],axis=0)
new_df

Time        V1        V2  ...       V28  Amount  Class
37906    39163.0 -0.363913  0.853399  ... -0.257103   18.49      0
65786    51746.0 -3.519614  2.536332  ... -0.069912    3.84      0
160537  113441.0  2.049175 -0.073552  ... -0.060345    3.96      0
78817    57720.0  1.156016 -0.194637  ...  0.015398   12.04      0
265574  161946.0 -0.483227  1.349745  ...  0.079387    7.00      0
...          ...       ...       ...  ...       ...     ...    ...
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[1092 rows x 31 columns]

In [101]:
x=new_df.drop(columns='Class',axis=1)
y=new_df['Class']

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2,random_state=1)

In [104]:
xtrain

Time         V1        V2  ...       V27       V28  Amount
131272   79540.0  -0.114361  1.036129  ...  0.129969  0.223924    0.20
100623   67571.0  -0.758469 -0.045410  ...  0.150606 -0.117140  549.06
267514  162804.0   2.046989 -0.033458  ... -0.017772 -0.071919    0.89
137705   82289.0  -1.464897  1.975528  ...  0.073796 -0.041570    1.00
189069  128251.0   2.052095 -0.160741  ... -0.079415 -0.076292    1.98
...          ...        ...       ...  ...       ...       ...     ...
120505   75851.0  -4.793667  3.418911  ...  0.328672  0.835395   99.85
42609    41170.0  -6.498086  4.750515  ...  1.415068  0.035124   83.38
150669   93860.0 -10.632375  7.251936  ... -1.416604 -0.488307  188.52
104154   68932.0  -0.772145 -0.155130  ...  0.043746  0.095472    9.99
251881  155542.0   1.868226  1.363077  ... -0.006629  0.017258    3.14

[873 rows x 30 columns]

**LinearRegression**

In [105]:
from sklearn.linear_model import LinearRegression
le=LinearRegression()

In [106]:
le.fit(xtrain,ytrain)

LinearRegression()

In [107]:
le.score(xtest,ytest)

0.6761806101416913

**LogisticRegression**

In [108]:
from sklearn.linear_model import LogisticRegression
m=LogisticRegression()

In [109]:
m.fit(xtrain,ytrain)

LogisticRegression()

In [110]:
m.score(xtest,ytest)

0.9634703196347032

In [111]:
pred=m.predict(xtest)
pred

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1])

In [112]:
from sklearn.metrics import classification_report

In [113]:
dr=classification_report(ytest,pred)

In [114]:
print(dr)

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       133
           1       0.96      0.94      0.95        86

    accuracy                           0.96       219
   macro avg       0.96      0.96      0.96       219
weighted avg       0.96      0.96      0.96       219



**KNeighborsClassifier**

In [115]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

In [116]:
k=KNeighborsClassifier(n_neighbors=10)

In [117]:
k.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=10)

In [118]:
k.score(xtrain,ytrain)*100

72.2794959908362

In [119]:
k.score(xtest,ytest)*100

67.12328767123287

In [120]:
kr=KNeighborsRegressor()
kr.fit(xtrain,ytrain)

KNeighborsRegressor()

In [121]:
kr.score(xtest,ytest)*100

0.8200734394124831

**DecisionTreeClassifier**

In [122]:
from sklearn.tree import DecisionTreeClassifier

In [123]:
d=DecisionTreeClassifier()

In [124]:
d.fit(xtrain,ytrain)
d.score(xtest,ytest)

0.9315068493150684

In [125]:
pred1=d.predict(xtest)
pred1

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1])

In [126]:
clr=classification_report(ytest,pred1)

In [127]:
print(clr)

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       133
           1       0.89      0.94      0.92        86

    accuracy                           0.93       219
   macro avg       0.93      0.93      0.93       219
weighted avg       0.93      0.93      0.93       219



**RandomForestClassifier**

In [128]:
from sklearn.ensemble import RandomForestClassifier


In [129]:
Ran=RandomForestClassifier()

In [130]:
Ran.fit(xtrain,ytrain)
Ran.score(xtest,ytest)

0.9680365296803652

In [131]:
pred3=Ran.predict(xtest)
pred3

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1])

In [132]:
clr1=classification_report(ytest,pred3)

In [133]:
print(clr1)

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       133
           1       0.99      0.93      0.96        86

    accuracy                           0.97       219
   macro avg       0.97      0.96      0.97       219
weighted avg       0.97      0.97      0.97       219



**Support Vector Machine(SVM)**

In [134]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [135]:
S=SVC()

In [136]:
S.fit(xtrain,ytrain)

SVC()

In [137]:
S.score(xtrain,ytrain)

0.565864833906071

In [138]:
S.score(xtest,ytest)

0.6529680365296804