In [32]:
import numpy as np

In [41]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b=a.astype(np.float64)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
c=b.astype(np.int64)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [48]:
str1 = np.array(['1','3','4','8','9'],dtype=np.string_)
str1

array([b'1', b'3', b'4', b'8', b'9'], dtype='|S1')

In [49]:
int_d=str1.astype(np.int64)
int_d

array([1, 3, 4, 8, 9], dtype=int64)

In [50]:
float_e=str1.astype(np.float64)
float_e

array([1., 3., 4., 8., 9.])

In [56]:
float_a=np.array([2.3,4.3,12.1,4.2,23.2])
float_a

array([ 2.3,  4.3, 12.1,  4.2, 23.2])

In [57]:
int_a=float_a.astype(np.int64)
int_a

array([ 2,  4, 12,  4, 23], dtype=int64)