In [1]:
import numpy as np

In [2]:
my_list= list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
arr= np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
b= [[[3,23,23],[6,7,8],[12,23,41]],[[2,3,4,],[5,6,7],[3,6,4]]]
b

[[[3, 23, 23], [6, 7, 8], [12, 23, 41]], [[2, 3, 4], [5, 6, 7], [3, 6, 4]]]

In [34]:
arr.ndim

1

In [35]:
c=np.array(b)
c

array([[[ 3, 23, 23],
        [ 6,  7,  8],
        [12, 23, 41]],

       [[ 2,  3,  4],
        [ 5,  6,  7],
        [ 3,  6,  4]]])

In [36]:
c.ndim

3

In [37]:
c.shape

(2, 3, 3)

In [38]:
c.dtype

dtype('int64')

In [46]:
zeros_array=np.zeros((2,5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
zeros_array.ndim

2

In [48]:
zeros_array.shape

(2, 5)

In [53]:
a=np.eye(4,4)
a


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
a.ndim

2

In [55]:
a.dtype

dtype('float64')

In [56]:
a.shape

(4, 4)

In [60]:
arran=np.arange(2,40,2)
arran

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [62]:
arrange_2=np.arange(11,100,2)
arrange_2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77,
       79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])